// apps/backend/src/domains/auth/controllers/auth.controller.ts

import {
  Controller,
  Post,
  Get,
  Body,
  Req,
  Res,
  UseGuards,
  HttpCode,
  HttpStatus,
  UnauthorizedException,
  UseInterceptors,
  ClassSerializerInterceptor,
  Ip,
  Headers,
} from '@nestjs/common';
import { Request, Response } from 'express';
import { TenantContext } from '../../../shared/types/tenant-context';
import { AuthService } from '../services/auth.service';
import { TenantService } from '../../tenant/services/tenant.service';
import { LoginDto } from '../dto/login.dto';
import { LoginResponse } from '../interfaces/login-response.interface';
import { JwtAuthGuard, SkipAuth } from '../../../shared/guards';
import { AuthRateLimit, SkipRateLimit } from '../../../shared/decorators/multitenant-rate-limit.decorator';

@Controller('auth')
export class AuthController {
  constructor(
    private readonly authService: AuthService,
    private readonly tenantService: TenantService,
  ) {}

  /** Issue a new JWT (in HttpOnly cookie) */
  @Post('login')
  @AuthRateLimit()
  @HttpCode(HttpStatus.OK)
  async login(
    @Body() dto: LoginDto,
    @TenantContext() tenant: { id: string; databaseUrl: string } | undefined,
    @Res({ passthrough: true }) res: Response,
  ): Promise<LoginResponse> {
    let tenantId: string | undefined = tenant?.id;
    
    // If tenantSubdomain is provided in the request body, resolve it to tenant ID
    if (dto.tenantSubdomain && !tenantId) {
      try {
        const tenantInfo = await this.tenantService.findBySubdomain(dto.tenantSubdomain);
        tenantId = tenantInfo.id;
        console.log(`[AUTH] Resolved tenant subdomain "${dto.tenantSubdomain}" to ID: ${tenantId}`);
      } catch (error) {
        console.error(`[AUTH] Failed to resolve tenant subdomain "${dto.tenantSubdomain}":`, error);
        throw new UnauthorizedException(`Invalid tenant: ${dto.tenantSubdomain}`);
      }
    }
    
    console.log(`[AUTH] Login attempt - Email: ${dto.email}, TenantID: ${tenantId || 'platform'}`);
    const { accessToken } = await this.authService.login(dto, tenantId);

    res.cookie('Authentication', accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      maxAge: 1000 * 60 * 60, // 1h in ms
    });

    return { accessToken };
  }

  /** Return the current user (validated from the cookie) */
  @Get('me')
  @SkipRateLimit() // /me endpoint used frequently for auth verification
  @UseGuards(JwtAuthGuard)
  @HttpCode(HttpStatus.OK)
  me(@Req() req: Request) {
    const user = req.user;
    if (!user) {
      throw new UnauthorizedException();
    }
    return user;
  }

  /** Get CSRF token */
  @Get('csrf-token')
  @SkipRateLimit() // CSRF tokens are fetched frequently for security
  @HttpCode(HttpStatus.OK)
  getCsrfToken(@Req() req: Request, @Res({ passthrough: true }) res: Response) {
    // The CSRF token is generated by the middleware and available as req.csrfToken()
    const token = (req as any).csrfToken?.();
    if (token) {
      res.setHeader('X-CSRF-Token', token);
      return { csrfToken: token };
    }
    return { csrfToken: null };
  }

  /** Clear the JWT cookie */
  @Post('logout')
  @AuthRateLimit()
  @HttpCode(HttpStatus.OK)
  async logout(@Res({ passthrough: true }) res: Response) {
    const baseDomain = process.env.BASE_DOMAIN || 'lvh.me';
    // Log for debugging
    console.log(`Clearing Authentication cookie for .${baseDomain}, ${baseDomain}, /`);
    res.clearCookie('Authentication', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      domain: `.${baseDomain}`,
      path: '/',
    });
    res.clearCookie('Authentication', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      domain: baseDomain,
      path: '/',
    });
    res.clearCookie('Authentication', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      path: '/',
    });
    res.clearCookie('Authentication');
    return { success: true };
  }
}
