# ===============================================
# 🚀 PROMETHEUS MONITORING CONFIGURATION
# ===============================================
# Production-ready monitoring setup for MultiTenant Shell

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'multitenant-shell'
    environment: 'production'

# Rule files
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # =============================================
  # APPLICATION METRICS
  # =============================================
  - job_name: 'multitenant-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['multitenant-backend:3000']
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    labels:
      service: 'backend'
      tier: 'application'

  # =============================================
  # INFRASTRUCTURE METRICS
  # =============================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    labels:
      service: 'database'
      tier: 'infrastructure'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    labels:
      service: 'cache'
      tier: 'infrastructure'

  # =============================================
  # SYSTEM METRICS
  # =============================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    labels:
      service: 'system'
      tier: 'infrastructure'

  # =============================================
  # CONTAINER METRICS
  # =============================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    labels:
      service: 'containers'
      tier: 'infrastructure'

  # =============================================
  # PROMETHEUS SELF-MONITORING
  # =============================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    labels:
      service: 'prometheus'
      tier: 'monitoring'

  # =============================================
  # TRAEFIK METRICS
  # =============================================
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'proxy'
      tier: 'infrastructure'

# =============================================
# RECORDING RULES FOR AGGREGATION
# =============================================
# These are defined in recording_rules.yml

# =============================================
# RETENTION AND STORAGE
# =============================================
# Configured via command line arguments in docker-compose.yml 