// Auto-generated navigation configuration
// This file is automatically generated from domain configuration

export const navigation = {
  "main": [
    {
      "title": "Overview",
      "href": "/docs",
      "icon": "Home",
      "description": "Get started with the application"
    },
    {
      "title": "Getting Started",
      "href": "/docs/getting-started",
      "icon": "Rocket",
      "description": "Quick setup and first steps",
      "items": [
        {
          "title": "Quick Start",
          "href": "/docs/getting-started/quickstart"
        },
        {
          "title": "Installation",
          "href": "/docs/getting-started/installation"
        },
        {
          "title": "Configuration",
          "href": "/docs/getting-started/configuration"
        },
        {
          "title": "First Steps",
          "href": "/docs/getting-started/first-steps"
        }
      ]
    },
    {
      "title": "Features",
      "href": "/docs/features",
      "icon": "Star",
      "description": "Explore core functionality",
      "items": [
        {
          "title": "Core Features",
          "href": "/docs/features/core"
        },
        {
          "title": "Advanced Features",
          "href": "/docs/features/advanced"
        },
        {
          "title": "Reporting",
          "href": "/docs/features/reporting"
        },
        {
          "title": "User Management",
          "href": "/docs/features/users"
        }
      ]
    },
    {
      "title": "Integrations",
      "href": "/docs/integrations",
      "icon": "Plug",
      "description": "Connect with third-party services",
      "items": [
        {
          "title": "API Integrations",
          "href": "/docs/integrations/api"
        },
        {
          "title": "Webhooks",
          "href": "/docs/integrations/webhooks"
        },
        {
          "title": "Third-party Services",
          "href": "/docs/integrations/services"
        }
      ]
    },
    {
      "title": "API Reference",
      "href": "/docs/api",
      "icon": "Code",
      "description": "Complete API documentation"
    },
    {
      "title": "Tutorials",
      "href": "/docs/tutorials",
      "icon": "BookOpen",
      "description": "Step-by-step guides"
    }
  ],
  "footer": [
    {
      "title": "Support",
      "href": "/docs/support"
    },
    {
      "title": "FAQ",
      "href": "/docs/faq"
    },
    {
      "title": "Contact",
      "href": "/docs/contact"
    }
  ]
};

export default navigation;
